[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[variables]
    # Vital para solucionar el error "could not find driver"
    PHP_EXTENSION_INSTALL = "pdo_mysql, mbstring, bcmath, xml"

[phases.build]
    cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.start]
    # Limpiamos caché, corremos migraciones y ejecutamos tu script de usuario admin
    cmd = "php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php db_init.php && php artisan serve --host=0.0.0.0 --port=$PORT"
